import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Footer2 from '../components/Footer2'
import Main1 from '../components/Main1'
import Main10 from '../components/Main10'
import Main11 from '../components/Main11'
import Main12 from '../components/Main12'
import Main13 from '../components/Main13'
import Main2 from '../components/Main2'
import Main3 from '../components/Main3'
import Main4 from '../components/Main4'
import Main5 from '../components/Main5'
import Main6 from '../components/Main6'
import Main7 from '../components/Main7'
import Main8 from '../components/Main8'
import Main9 from '../components/Main9'
import Navbar from '../components/Navbar'
import Table from '../components/Table'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-white'>
      
      <Head>
        <title>Truntio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main1/>
      <Main2/>
      <Main3/>
      <Main4/>
      <Table/>
      <Main5/>
      <Main6/>
      <Main7/>
      <Main8/>
      <Main9/>
      <Main10/>
      <Main11/>
      <Main12/>
      <Main13/>
      <Footer/>
      <Footer2/>

    </div>
  )
}
